import { ChatBubbleLeftRightIcon } from '@heroicons/react/24/outline';
import { getUnitIcon } from '@/utils/icons';
import { Unit } from '@/types';

/**
 * Interface defining the props for the UnitCard component
 */
interface UnitCardProps {
  unit: Unit;                    // The unit object containing title, number, and topics
  onSelect: (unit: Unit) => void; // Callback function when the unit card is clicked
}

/**
 * UnitCard Component
 * 
 * A clickable card component that displays a unit's information in an attractive,
 * interactive format. Each card represents one educational unit and serves as an
 * entry point to explore the unit's topics and learning materials.
 * 
 * Key Features:
 * - Interactive card with hover animations and visual feedback
 * - Unit-specific icons generated by utility function
 * - Topic count display for quick content overview
 * - Responsive design with proper touch targets for mobile
 * - Accessibility features including focus states and semantic markup
 * - Dark mode support with theme-aware styling
 * - Smooth animations and transitions for enhanced UX
 * 
 * Visual Design:
 * - Rounded corners and subtle shadows for modern card appearance
 * - Blue color scheme with hover state enhancements
 * - Unit number badge for quick identification
 * - Icon container with scaling animation on hover
 * - Progressive disclosure with "Explore materials" call-to-action
 * 
 * Interaction States:
 * - Default: Clean card layout with visible content
 * - Hover: Slight scale increase, enhanced shadow, visible CTA
 * - Focus: Blue ring outline for keyboard navigation
 * - Active: Triggers selection callback to parent component
 * 
 * Content Structure:
 * 1. Unit Icon: Visual identifier based on unit number
 * 2. Unit Badge: Displays "Unit X" label
 * 3. Unit Title: Full title with text truncation if needed
 * 4. Topic Count: Shows number of available topics
 * 5. Call-to-Action: Appears on hover to encourage interaction
 * 
 * Accessibility Features:
 * - Button element for proper keyboard navigation
 * - Focus ring for visual focus indication
 * - Semantic structure with heading hierarchy
 * - Descriptive text for screen readers
 * 
 * @param unit - Unit object containing number, title, and topics array
 * @param onSelect - Function called when user clicks the card
 */
export function UnitCard({ unit, onSelect }: UnitCardProps) {
  return (
    <button
      onClick={() => onSelect(unit)}
      className="group bg-white dark:bg-slate-800 rounded-2xl shadow-lg border border-slate-200 dark:border-slate-700 p-6 text-left transition-all duration-300 hover:scale-105 hover:shadow-xl focus:outline-none focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-800"
      aria-label={`Explore Unit ${unit.unit_number}: ${unit.unit_title} (${unit.topics.length} topics)`}
    >
      <div className="text-center space-y-4">
        {/* Unit Icon Container */}
        {/* Icon scales up on hover for interactive feedback */}
        <div className="w-16 h-16 bg-blue-100 dark:bg-blue-900 rounded-2xl flex items-center justify-center text-2xl mx-auto transition-transform group-hover:scale-110">
          {getUnitIcon(unit.unit_number)} {/* Dynamic icon based on unit number */}
        </div>
        
        {/* Unit Information Section */}
        <div className="space-y-3">
          {/* Unit Badge and Title */}
          <div className="space-y-2">
            {/* Unit number badge with blue theming */}
            <span className="inline-block px-3 py-1 bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 rounded-full text-sm font-medium">
              Unit {unit.unit_number}
            </span>
            
            {/* Unit title with responsive text sizing and truncation */}
            <h3 className="font-bold text-lg leading-tight text-slate-900 dark:text-white line-clamp-3">
              {unit.unit_title}
            </h3>
          </div>
          
          {/* Unit Statistics */}
          {/* Shows topic count with icon for quick content overview */}
          <div className="flex items-center justify-center gap-4 text-sm text-slate-500 dark:text-slate-400">
            <span className="flex items-center gap-1">
              <ChatBubbleLeftRightIcon className="w-4 h-4" />
              {unit.topics.length} topics
            </span>
          </div>
        </div>

        {/* Call-to-Action */}
        {/* Hidden by default, appears on hover to encourage interaction */}
        <div className="text-blue-600 dark:text-blue-400 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity duration-200">
          Explore materials →
        </div>
      </div>
    </button>
  );
}